name: Jason Loo
description: Title to be Determined

# url: "http://localhost:4000"
url: "http://nosajool.github.io/"

paginate: 5

markdown: rdiscount

permalink: pretty

sass:
    sass_dir: assets/css