#-------------------------------
# General Site Settings

title: Jason Loo
description: Software Engineering Student at the University of Waterloo
email: jmloo@uwaterloo.ca


#-------------------------------
# Sidebar section
sidebaritems:
- { name: About, id: about-me-button, class: "fa fa-info fa-lg", link: "#" }
- { name: Projects, id: projects-button, class: "fa fa-paper-plane fa-lg", link: "#" }
- { name: Blog, id: blog-button, class: "fa fa-pencil fa-lg", link: "#" }
- { name: Github, id: "", class: "fa fa-github fa-lg", link: "https://github.com/Nosajool" }
- { name: LinkedIn, id: "", class: "fa fa-linkedin fa-lg", link: "https://www.linkedin.com/pub/jason-loo/85/703/75a" }
- { name: Twitter, id: "", class: "fa fa-twitter fa-lg", link: "https://twitter.com/J_waterLoo" }

#-------------------------------
# About Section

intro: >
  ### Hi, my name is **Jason**

  I'm a Software Engineering student at the University of Waterloo currently in 2A.

school:
- term: Co-op 1
  season: Spring 2014
  courses:
  - code: PD 20
    title: Engineering Workplace Skills I Developing Reasoned Conclusions
- term: 1B
  season: Winter 2014
  courses:
  - code: CS 138
    title: Introduction to Data Abstraction and Implementation
    cs: true
  - code: ECE 106
    title: Physics of Electrical Engineering 2
  - code: ECE 124
    title: Digital Circuits and Systems
  - code: MATH 119
    title: Calculus 2 for Engineering
  - code: MATH 135
    title: Algebra for Honours Mathematics
- term: 1A
  season: Fall 2013
  courses:
  - code: CS 137
    title: Programming Principles
    cs: true
  - code: ECE 105
    title: Physics of Electrical Engineering 1
  - code: ECE 140
    title: Linear Circuits
  - code: MATH 115
    title: Linear Algebra for Engineering
  - code: MATH 117
    title: Calculus 1 for Engineering
  - code: SE 101
    title: Introduction to Methods of Software Engineering
    cs: true


teams:
- { name: Ottawa Senators, image: senators_logo.png }
- { name: Washington Capitals, image: capitals_logo.png }
- { name: Counter Logic Gaming, image: clg_logo.png }


#-------------------------------
# Work Section

projects:
- { name: Kik The Code, folder: 'kik-the-code', icon: main.png, description: "Did stuff", tech: "Node JS, Express JS, Socket IO, JQuery, Kik API, Bootstrap" }
- { name: League of Valor, icon: icon.png, folder: 'league-of-valor', tech: "Ruby On Rails, Riot API, Bootstrap" }
- { name: Questionit, folder: 'questionit', icon: icon.PNG, tech: "Ruby On Rails" }
- { name: Github Issue Generator, icon: icon.PNG, tech: "AngularJS, Bootstrap", folder: 'github-issue-generator' }
- { name: Vion Genesis, folder: 'vion-genesis', tech: "PHP, MySQL", icon: icon.png }
- { name: Smack Down, folder: 'smack-down', tech: "Java, Java Swing", icon: icon.png }